### PR TITLE
add Gradle to run on Travis

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by commonsguy** [comment]
Quoting [the contribution guidelines](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md):

> In general, you should open a bug report or feature request issue first, before submitting a pull request".

I do not use Travis CI and have no interest in maintaining a Travis CI file. I also **very specifically** do not publish a `gradle-wrapper.jar` file or `gradlew`/`gradlew.bat` files, as *nobody* should be trusting binaries from random GitHub repos like this one. The Gradle Wrapper is cute, but from a developer security standpoint, it is dreadful.

**Comment by hannesa2** [comment]
At least it's checked in and you could verify if it's bad.
When you build it I should trust them more ?
It's vice versa

**Comment by commonsguy** [comment]
> At least it's checked in and you could verify if it's bad.

Nobody does that.

Also, AFAIK, adding the automated SHA-256 hash check will crash Android Studio, because AFAIK they never fixed the bug that I reported years ago.

You should get your own Gradle Wrapper from your own copy of Gradle.

**Comment by hannesa2** [comment]
> Nobody does that.
But you can if you really want. Current situation is worst

**Comment by commonsguy** [comment]
> Please read about this https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification

I am very aware of that property. [It still crashes Android Studio 3.2](https://issuetracker.google.com/issues/37126713#comment6), though I have not tested it again with 3.2.1.

**Pull request closed without merging**
